version: '3.8'

services:
  contexto_game_db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: contexto_game_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  contexto_web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
        - contexto_game_db
    networks:
        - contexto_game

volumes:
  postgres_data:

networks:
  contexto_game:
