# Generated by Django 5.1.4 on 2025-01-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='words',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='word_to_guess',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_word', models.CharField(max_length=100)),
                ('similarity_score', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
